// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkA1q_BoI7nmTx1sGni5M_J97vsKcmNHE',
    appId: '1:708200642604:web:abbe51df62d96b6c61f989',
    messagingSenderId: '708200642604',
    projectId: 'fuel-management-26729',
    authDomain: 'fuel-management-26729.firebaseapp.com',
    storageBucket: 'fuel-management-26729.appspot.com',
    measurementId: 'G-YSFTFXS02R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGjDV5pAwurZaNHQG8p4q1cCFXvo_aukc',
    appId: '1:708200642604:android:340542c32f23794e61f989',
    messagingSenderId: '708200642604',
    projectId: 'fuel-management-26729',
    storageBucket: 'fuel-management-26729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-L75wWEzXcNrwcfe-wI0S-b-xBtTWrfc',
    appId: '1:708200642604:ios:cb762b8a49912dd861f989',
    messagingSenderId: '708200642604',
    projectId: 'fuel-management-26729',
    storageBucket: 'fuel-management-26729.appspot.com',
    iosBundleId: 'com.scalar.fuelmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-L75wWEzXcNrwcfe-wI0S-b-xBtTWrfc',
    appId: '1:708200642604:ios:12470b06961c97e161f989',
    messagingSenderId: '708200642604',
    projectId: 'fuel-management-26729',
    storageBucket: 'fuel-management-26729.appspot.com',
    iosBundleId: 'com.example.deepcalc',
  );
}
